# 7-base_geometry.txt
===============================
How to 7-base_geometry.py
===============================

   >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
   >>> bg = BaseGeometry()
   >>> bg.integer_validator("my_int", 12)
   >>> bg.integer_validator("width", 89)

Non-Integers
===========

Raise error message in cases that one of the variables are not integers
or are less than 0 or 0

   >>> bg.integer_validator("name", "John")
   Traceback (most recent call last):
   TypeError: name must be an integer

   >>> bg.integer_validator("age", 0)
   Traceback (most recent call last):
   ValueError: age must be greater than 0

   >>> bg.integer_validator("distance", -4)
   Traceback (most recent call last):
   ValueError: distance must be greater than 0

   >>> bg.integer_validator()
   Traceback (most recent call last):
   TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

   >>> bg.integer_validator(1)
   Traceback (most recent call last):
   TypeError: integer_validator() missing 1 required positional argument: 'value'

   >>> bg.integer_validator("half", 1.5)
   Traceback (most recent call last):
   TypeError: half must be an integer

   >>> bg.integer_validator(2, 1.5)
   Traceback (most recent call last):
   TypeError: 2 must be an integer

   >>> bg.integer_validator(2, "John")
   Traceback (most recent call last):
   TypeError: 2 must be an integer

   >>> bg.integer_validator("name", [1, 2])
   Traceback (most recent call last):
   TypeError: name must be an integer

   >>> bg.integer_validator([2, 6], "John")
   Traceback (most recent call last):
   TypeError: [2, 6] must be an integer

   >>> bg.integer_validator(distance, -4)
   Traceback (most recent call last):
   NameError: name 'distance' is not defined

   >>> bg.integer_validator("distance", name)
   Traceback (most recent call last):
   NameError: name 'name' is not defined

   >>> bg.area()
   Traceback (most recent call last):
   Exception: area() is not implemented

   >>> bg.integer_validator("age", True)
   Traceback (most recent call last):
   TypeError: age must be an integer

   >>> bg.integer_validator("age", {3, 4})
   Traceback (most recent call last):
   TypeError: age must be an integer

   >>> bg.integer_validator("age", None)
   Traceback (most recent call last):
   TypeError: age must be an integer

   >>> bg.integer_validator("age", (4,))
   Traceback (most recent call last):
   TypeError: age must be an integer
